# Generated by Django 4.2.9 on 2024-04-11 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='UserProfile',
        ),
    ]
