# Generated by Django 4.2.9 on 2024-04-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_rename_shippingaddress_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
